import Head from "next/head";
export default function Home() {
  return (
  
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
    </div>
   
  );
}
